# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
   include:
     - main
 paths:
   include:
   - Infra/*

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  displayName: 'Build infra'
  inputs:
    azureSubscription: 'Azure MPN - yuriburger'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az bicep build --file main.bicep'
    workingDirectory: 'Infra'

- task: PublishBuildArtifacts@1
  displayName: 'Publish infra'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/Infra/main.json'
    ArtifactName: 'infra'
    publishLocation: 'Container'
