trigger: none

pr: none

pool:
  vmImage: ubuntu-latest

stages:

- stage: Build
  jobs:
  - job: Build
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Restore API'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        workingDirectory: './Code'

    - task: DotNetCoreCLI@2
      displayName: 'Test API'
      inputs:
        command: 'test'
        projects: '**/*.csproj'
        arguments: '--no-restore --verbosity normal'
        workingDirectory: './Code'

    - task: DotNetCoreCLI@2
      displayName: 'Build API'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration Release --no-restore'
        workingDirectory: './Code'
    
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: 'Azure ACR - yuriburger'
        repository: 'ampedapi'
        command: 'buildAndPush'
        Dockerfile: './Code/Amped.API/Dockerfile'

  