trigger:
 branches:
   include:
     - main
 paths:
   include:
   - Infra/*

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: AzureCLI@2
      displayName: 'Build infra'
      inputs:
        azureSubscription: 'Azure MPN - yuriburger'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az bicep build --file main.bicep'
        workingDirectory: 'Infra'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish infra'
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/Infra/main.json'
        ArtifactName: 'infra'
        publishLocation: 'Container'
