trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:

- checkout: self

- task: AzureStaticWebApp@0
  inputs:
    app_location: '/public'
    skip_app_build: true
    azure_static_web_apps_api_token: '$(DEPLOYMENT_TOKEN)'