trigger: none
#  branches:
#    include:
#      - main
#  paths:
#    include:
#    - App/*

pr: none

pool:
  vmImage: ubuntu-latest

stages:

- stage: Build
  jobs:
  - job: Build
    steps:

    - checkout: self
    - task: Npm@1
      displayName: Install dependencies
      inputs:
        command: 'ci'
        workingDir: 'App'
    
    - task: Npm@1
      displayName: Build
      inputs:
        command: 'custom'
        workingDir: 'App'
        customCommand: 'run build'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          ls -al

