trigger:
 branches:
   include:
     - main
 paths:
   include:
   - Code/*

pr: none

pool:
  vmImage: ubuntu-latest

stages:

- stage: RunVulnerabilityTest
  jobs:
    
  - job: Test
    container: owasp/zap2docker-bare:2.11.1
    steps:
    - script: printenv

- stage: Build
  jobs:
  - job: Build
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Restore API'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        workingDirectory: './Code'

    - task: DotNetCoreCLI@2
      displayName: 'Test API'
      inputs:
        command: 'test'
        projects: '**/*.csproj'
        arguments: '--no-restore --verbosity normal'
        workingDirectory: './Code'

    - task: DotNetCoreCLI@2
      displayName: 'Build API'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration Release --no-restore'
        workingDirectory: './Code'

- stage: DeployTest
  jobs:
  - deployment: APItoAzure
    displayName: 'Deploy to Azure'
    environment: 'AzureTest'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: DotNetCoreCLI@2
            displayName: 'Publish API'
            inputs:
              command: 'publish'
              publishWebProjects: true
              workingDirectory: './Code'
          - task: AzureWebApp@1
            displayName: 'Deploy API'
            inputs:
              azureSubscription: 'Azure MPN - yuriburger'
              appType: 'webAppLinux'
              appName: 'app-amped-api-qa-westeu-001'
              package: '$(System.DefaultWorkingDirectory)/Code/**/*.zip'

