trigger:
 branches:
   include:
     - main
 paths:
   include:
   - Code/*

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        workingDirectory: './Code'

