trigger: none

pr: none

pool:
  vmImage: ubuntu-latest

stages:

- stage: Build
  jobs:
  - job: Build
    steps:
        
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: 'Azure ACR - yuriburger'
        repository: 'ampedapi'
        command: 'buildAndPush'
        Dockerfile: './Code/Amped.API/Dockerfile'
        buildContext: './Code'
        tags: '$(Build.BuildId)'

  
