trigger:
  branches:
    include:
      - main
  paths:
    include:
    - App/*

pr: none

pool:
  vmImage: ubuntu-latest

stages:

- stage: Build & Deploy
  jobs:
  - job: Build
    steps:

    - checkout: self
    - task: Npm@1
      displayName: Install dependencies
      inputs:
        command: 'ci'
        workingDir: 'App'
    
    - task: Npm@1
      displayName: Build
      inputs:
        command: 'custom'
        workingDir: 'App'
        customCommand: 'run build'
    - task: AzureStaticWebApp@0
      displayName: Deploy
      inputs:
        app_location: 'App/public'
        skip_app_build: true
        azure_static_web_apps_api_token: '$(DEPLOYMENT_TOKEN)'

