trigger: none

pr: none

pool:
  vmImage: ubuntu-latest

stages:

- stage: Build
  jobs:
  - job: Build
    steps: 
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: 'Azure ACR - yuriburger'
        repository: 'ampedapi'
        command: 'buildAndPush'
        Dockerfile: './Code/Amped.API/Dockerfile'
        buildContext: './Code'
        tags: '$(Build.BuildId)'

  
- stage: DeployTest
  jobs:
    - deployment: APIToAzure
      displayName: 'Deploy to Azure'
      environment: 'AzureTest'
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - task: AzureCLI@2
              displayName: 'Deploy template'
              env:
                MY_RABBITMQ_PASS: $(RABBITMQ_PASS)
                MY_REGISTRY_PASS: $(REGISTRY_PASS)
              inputs:
                azureSubscription: 'Azure MPN - yuriburger'
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az deployment group create  `
                  --template-file $(Build.SourcesDirectory)/Infra/api.bicep `
                  --resource-group 'totallyamped.tech' `
                  --parameters containerImage=amped.azurecr.io/ampedapi:$(Build.BuildId) `
                  rabbitUsername=$env:RABBITMQ_USER rabbitPassword=$env:MY_RABBITMQ_PASS `
                  containerPort=80 registry=amped.azurecr.io `
                  registryUsername=$env:REGISTRY_USER registryPassword=$env:MY_REGISTRY_PASS
                  

