trigger:
 branches:
   include:
     - main
 paths:
   include:
   - Infra/*

pr: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: AzureCLI@2
      displayName: 'Build infra'
      inputs:
        azureSubscription: 'Azure MPN - yuriburger'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az bicep build --file main.bicep'
        workingDirectory: 'Infra'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish infra'
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/Infra/main.json'
        ArtifactName: 'infra'
        publishLocation: 'Container'
- stage: DeployTest
  jobs:
  - deployment: InfratoAzure
    displayName: 'Deploy to Azure'
    environment: 'AzureTest'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureCLI@2
            displayName: 'Deploy bicep template'
            inputs:
              azureSubscription: 'Azure MPN - yuriburger' 
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment group create  `
                --template-file $(Build.SourcesDirectory)/Infra/main.bicep `
                --resource-group 'totallyamped.tech' `
                --parameters env=qa 
