// <auto-generated />

using Amped.Bookmarks.Infrastructure;
using Amped.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Amped.Infrastructure.Migrations
{
    [DbContext(typeof(AmpedDbContext))]
    [Migration("20220325154857_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("Amped.Bookmarks.Core.Bookmark", b =>
                {
                    b.Property<string>("Uri")
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Read")
                        .HasColumnType("INTEGER");

                    b.HasKey("Uri", "Owner");

                    b.ToTable("Bookmarks");
                });
#pragma warning restore 612, 618
        }
    }
}
