# This is the workflow that will build and analyze the Java source code

name: CI - Profile - API

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # and only for the Code directory of the repo
  #push:
  #  branches: [ main ]
  #  paths:
  #  - Profile/amped-profile/**
  #pull_request:
  #  branches: [ main ]
  #  paths:
  #  - Profile/amped-profile/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish_docker_images:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './Profile/amped-profile'

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: ./mvnw package -Dnative -DskipTests -Dquarkus.native.container-build=true

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: vxcompanybv/amped-profile-api

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./Profile/amped-profile
          file: ./Profile/amped-profile/Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
