# This is the workflow that will build and analyze the Java source code

name: CI - Profile - API

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # and only for the Code directory of the repo
  #push:
  #  branches: [ main ]
  #  paths:
  #  - Profile/amped-profile/**
  #pull_request:
  #  branches: [ main ]
  #  paths:
  #  - Profile/amped-profile/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './Profile/amped-profile'

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: ./mvnw install -Dquarkus.native.container-build=true
