# This is the workflow that will build the Azure Bicep files

name: CI - Infra

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # and only for the Infra directory of the repo
  push:
    branches: [ main ]
    paths:
    - 'Infra/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'Infra/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Bicep Build
        uses: Azure/bicep-build-action@v1.0.0
        with:
          bicepFilePath: './Infra/main.bicep'
          outputFilePath: './Infra/azuredeploy.json'
